require:
  - rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - lib/templates/**/*
    - db/migrate/*
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - config/environments/*
Rails/FilePath:
  Enabled: false
Rails/OutputSafety:
  Exclude:
    - 'app/inputs/*'
Rails/ApplicationRecord:
  Exclude:
    - 'config/initializers/version.rb'
Rails/ActionControllerTestCase:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveSupportExtensionsInModel:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FreezeTime:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: true
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/StripHeredoc:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedIgnoredColumns:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/WhereNotWithMultipleConditions:
  Enabled: true